
defaults:
  - _self_
  - model: little_transformer #mnist_classifier,little_transformer #nano_gpt
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

log_dir: reports 
output_dir: outputs
hydra/job_logging: none